[package]
name = "timetracker"
version = "0.1.0"
edition = "2024"

[dependencies]
assert_cmd = "2.0.17"
clap = "4.5.36"
csv = "1.3.1"
env_logger = "0.11.8"
log = "0.4.27"
regex = "1.11.1"
tempfile = "3.19.1"

[dev-dependencies]
dedent = "0.1.1"
